### PR TITLE
Exatrkx machine

### PR DESCRIPTION
**Pull request by benjaminhuth**
This is a container description for the acts Exa.Trkx Plugin. It installs the extra dependencies cugraph, libtorch and ONNX.

### CODE REVIEW

**Comment by paulgessinger** [comment]
I don't understand why the CI doesn't run on this one...

**Comment by paulgessinger** [comment]
In any case, could you add this image to the CI workflow?

**Comment by benjaminhuth** [comment]
> In any case, could you add this image to the CI workflow?

So based on my fork of this repository? I thought that we must first merge this PR before it can find the Dockerfile...

**Comment by paulgessinger** [comment]
No i meant modifying the CI yaml file in this repo so that it BUILDs the docker image.

**Comment by benjaminhuth** [comment]
Ah okay, sure! I wasn't aware of this yaml file here

**Comment by benjaminhuth** [comment]
There is this comment in the yaml file... Seems like this is the problem?

```
# on pull_request does not work with forks since the jobs will try to push
# to the target registry but run only with the privileges of the fork.
#- pull_request
```

**Comment by paulgessinger** [comment]
Ah yeah, that's why 😄

**Comment by paulgessinger** [comment]
Ok, I built and pushed it locally, so the CI should now be able to build. Merging this now.

**Pull request merged**
