### PR TITLE
Update HepMC3 download URL

### PR DESCRIPTION
**Pull request by paulgessinger**

### CODE REVIEW

**Review by andiwand — APPROVED** [review]
just saw this breaking in the other PR - thanks!

**Comment by paulgessinger** [comment]
Fix doesn't seem to be working right now though. Need to look into it again, probably I messed up the URL.

**Comment by paulgessinger** [comment]
Might be a transient failure.

**Comment by paulgessinger** [comment]
@andiwand now with the push trigger gone, I think the jobs are not shown on the PR at all anymore.

**Comment by andiwand** [comment]
> @andiwand now with the push trigger gone, I think the jobs are not shown on the PR at all anymore.

I can see them and all 24 seem to have passed 👍 Maybe temporary UI bug?

**Pull request merged**
