### PR TITLE
Add CentOS7 LCG 97/98 images

### PR DESCRIPTION
**Pull request by msmk0**
Add new images based on LCG 97apython with gcc 9 and LCG 98python3 with gcc 10. These replace the existing LCG 95/96 images.

### CODE REVIEW

**Comment by msmk0** [comment]
@paulgessinger I suggest we wait until the CI build in acts-project/acts#615 runs through. Then we merge this PR and #24 and create a new container tag.

**Comment by paulgessinger** [comment]
Sounds good

**Comment by msmk0** [comment]
@paulgessinger acts-project/acts#615 seems to run through. I think we can merge this.

**Comment by msmk0** [comment]
@paulgessinger One more thing: I am considering renaming the LCG containers to
```
centos7-lcg97apython3-gcc9
centos7-lcg98python3-gcc10
```
since the compiler version is of some importance. Thoughts?

**Comment by paulgessinger** [comment]
Yeah maybe it makes it more clear what's used where.

**Comment by msmk0** [comment]
@paulgessinger The LCG images are renamed.

**Review by paulgessinger — APPROVED** [review]

**Pull request merged**
