### PR TITLE
add image with Ubuntu20.04 and CUDA11 and our deps

### PR DESCRIPTION
**Pull request by paulgessinger**
This is again based on nvidias image which I add our dependencies to. I briefly tested this by building the ACTS CUDA plugin, so I think it works.

/cc @beomki-yeo

### CODE REVIEW

**Comment by beomki-yeo** [comment]
Can you downgrade cuda to 11.3? I remember the cuda seed finding didn't work on cuda 11.4, which I need to investigate later

**Comment by paulgessinger** [comment]
I think so. I switched the base image to `11.3.0`.

**Comment by beomki-yeo** [comment]
Thanks. Let's merge it and let me give it a try in traccc

**Comment by paulgessinger** [comment]
Ok I quickly checked locally if that version also builds, and it seems fine to me. So merging this.

**Comment by paulgessinger** [comment]
@beomki-yeo The package should be available here now: https://github.com/acts-project/machines/pkgs/container/ubuntu2004_cuda, I think the CI should also push a version once it completes, and then I'll make a new container tag. Right now you'll have to pull `latest`

**Pull request merged**
