### PR TITLE
Add an updated APT repo key for the ROCm repository

### PR DESCRIPTION
**Pull request by paulgessinger**

### CODE REVIEW

**Review by krasznaa — APPROVED** [review]
As discussed on Skype, this is all good. :smile: (At least as long as the CI collaborates as well. :stuck_out_tongue:)

**Comment by krasznaa** [comment]
:confused: Was this a temporary glitch with the Intel repository? Since the setup of that one should accept the key of the repository **just before** installing the oneAPI packages. Strange...

**Comment by paulgessinger** [comment]
It seems like their package file changed and the checksum check fails... I'll try to update the PR.

**Comment by paulgessinger** [comment]
Locally the image seems to build fine for me. Could you try on your end @krasznaa ?

**Comment by krasznaa** [comment]
:confused: That image builds fine on my machine as well. The download of the Intel `.deb` packages was very slow, it went with ~10 Mb/s. But eventually it succeeded, and the build finished successfully.

Could GitHub be keeping some sort of (Squid) cache of Intel's repository, making the new `.deb` packages and their summary files get out of sync from the build node's perspective? This would sound like an overly complicated explanation, but I can't come up with anything better at the moment...

**Comment by paulgessinger** [comment]
Seems to have run through now. Let's try.

**Pull request merged**
