### PR TITLE
fix: bump DD4hep version for python 3.12

### PR DESCRIPTION
**Pull request by AJPfleger**
DD4hep `v1-27` uses `import imp` which is not supported anymore in python 3.12. This was fixed in `v1-28`.

This is necessary for Ubuntu 24.04, since it comes with python 3.12. Should we still upgrade also the older versions if possible?

### CODE REVIEW

**Comment by stephenswat** [comment]
For clarification, is this import deprecated or does it actually crash the code? Either way this is a good change.

**Comment by paulgessinger** [comment]
It was deprecated and has finally been removed in 3.12

**Comment by AJPfleger** [comment]
It appeared in
- https://github.com/acts-project/acts/pull/3227

during the test
- https://github.com/acts-project/acts/actions/runs/9350413380/job/25736137405?pr=3227

so as @paulgessinger just said, it does not exist anymore.

```
_____________________ test_edm4hep_simhit_particle_reader ______________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/__w/acts/acts/Examples/Python/tests/test_reader.py", line 284, in generate_input_test_edm4hep_simhit_reader
    ddsim.run()
  File "/usr/local/lib/python3.12/site-packages/DDSim/DD4hepSimulation.py", line 296, in run
    import DDG4
  File "/usr/local/lib/ROOT/_facade.py", line 154, in _importhook
    return _orig_ihook(name, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/DDG4.py", line 13, in <module>
    from dd4hep_base import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/ROOT/_facade.py", line 154, in _importhook
    return _orig_ihook(name, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dd4hep_base.py", line 13, in <module>
    import imp
  File "/usr/local/lib/ROOT/_facade.py", line 154, in _importhook
    return _orig_ihook(name, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'
"""
```

**Comment by stephenswat** [comment]
Alright, well - my approval for this. :slightly_smiling_face:

**Comment by AJPfleger** [comment]
Could we get this in with the next release? Somehow, it did not make it into the last 2 releases ૮ ⸝⸝o̴̶̷᷄ ·̭ o̴̶̷̥᷅⸝⸝  ྀིა

I would need it for updating the ACTS CI:
- https://github.com/acts-project/acts/pull/3227

**Pull request merged**
