### PR TITLE
Add a new machine with Ubuntu 20.04 and Futhark

### PR DESCRIPTION
**Pull request by paulgessinger**
I would like to use this in the traccc CI in the future. Builds upon an existing image with CUDA, so the overhead of this should be relatively small.

Originally #70.

### CODE REVIEW

**Comment by stephenswat** [comment]
Is the failure here expected or did I mess something up?

**Comment by paulgessinger** [comment]
Might be a perm thing and I might have to build and push this manually to start off with.

**Comment by stephenswat** [comment]
Hey, not to rush you but is there anything we can do to move forward on this PR? Would be useful for testing traccc code.

**Comment by paulgessinger** [comment]
I didn't follow up here. I'll try to do that this week.

**Comment by stephenswat** [comment]
Superb, thank you; there's no real rush though so don't worry.

**Comment by stephenswat** [comment]
Let's close this, this is no longer needed.

**Pull request closed without merging**
